{% set name = "findent" %}
{% set version = "4.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/project/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 62144eb84bda93d21241a6963ef973f92778bca7c915bfea9b38973774e85c7e

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - bison
    - flex
    - libtool
    - automake
    - autoconf
    - make
    - perl

test:
  commands:
    - findent --version

about:
  home: https://sourceforge.net/projects/{{ name }}/
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - COPYING
  summary: Indents/beautifies/converts Fortran sources.
  doc_url: https://sourceforge.net/p/{{ name }}/wiki/
  dev_url: https://sourceforge.net/p/{{ name }}/code/HEAD/tree/

extra:
  recipe-maintainers:
    - awvwgk
    - gnikit
