{% set name = "findent" %}
{% set version = "4.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/project/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6e4ea2fdac92f62dd1a8ec13a60d98c20cbd1b21df1e65edfcda104c4717aa80

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - bison
    - flex
    - libtool
    - automake
    - autoconf
    - make
    - perl

test:
  commands:
    - findent --version

about:
  home: https://sourceforge.net/projects/{{ name }}/
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - COPYING
  summary: Indents/beautifies/converts Fortran sources.
  doc_url: https://sourceforge.net/p/{{ name }}/wiki/
  dev_url: https://sourceforge.net/p/{{ name }}/code/HEAD/tree/

extra:
  recipe-maintainers:
    - awvwgk
    - gnikit
